"""
Supabase Service — persistence layer for user data.

Handles SRS card scheduling, attempt logging, study-plan storage,
and weak-topic analytics via the Supabase REST API.
"""

from __future__ import annotations

import os
from datetime import date, datetime, timezone
from typing import Any

from dotenv import load_dotenv
from supabase import create_client, Client

load_dotenv()

# ── Singleton client ─────────────────────────────────────────────────
_supabase_instance: Client | None = None


def get_supabase() -> Client:
    """Return a singleton Supabase client.

    Reads ``SUPABASE_URL`` and ``SUPABASE_SERVICE_KEY`` from the
    environment on first call.

    Returns:
        A configured ``supabase.Client``.
    """
    global _supabase_instance
    if _supabase_instance is None:
        url: str = os.environ["SUPABASE_URL"]
        key: str = os.environ["SUPABASE_SERVICE_KEY"]
        _supabase_instance = create_client(url, key)
    return _supabase_instance


# ── SRS helpers ──────────────────────────────────────────────────────
def fetch_due_cards(user_id: str) -> list[dict[str, Any]]:
    """Fetch flashcards whose next review date is today or earlier.

    Args:
        user_id: UUID of the learner.

    Returns:
        A list of card rows (dicts) that are due for review.
    """
    today_iso: str = date.today().isoformat()
    response = (
        get_supabase()
        .table("cards")
        .select("*")
        .eq("user_id", user_id)
        .lte("next_review", today_iso)
        .execute()
    )
    return response.data


def update_card_after_review(
    card_id: str,
    ease_factor: float,
    interval_days: int,
) -> dict[str, Any]:
    """Persist updated SM-2 parameters for a card after review.

    Args:
        card_id: UUID of the card.
        ease_factor: New ease factor (≥ 1.3).
        interval_days: Days until next review.

    Returns:
        The updated card row.
    """
    next_review: str = (
        date.today().__class__.fromordinal(
            date.today().toordinal() + interval_days
        ).isoformat()
    )
    response = (
        get_supabase()
        .table("cards")
        .update(
            {
                "ease_factor": ease_factor,
                "interval_days": interval_days,
                "next_review": next_review,
            }
        )
        .eq("id", card_id)
        .execute()
    )
    return response.data


# ── Attempt logging ──────────────────────────────────────────────────
def log_attempt(
    user_id: str,
    card_id: str,
    score: int,
    time_seconds: int,
) -> dict[str, Any]:
    """Record a single review attempt for analytics.

    Args:
        user_id: UUID of the learner.
        card_id: UUID of the practiced card.
        score: Self-reported recall score (0-5).
        time_seconds: Time spent on this attempt in seconds.

    Returns:
        The inserted attempt row.
    """
    response = (
        get_supabase()
        .table("attempts")
        .insert(
            {
                "user_id": user_id,
                "card_id": card_id,
                "score": score,
                "time_seconds": time_seconds,
                "created_at": datetime.now(timezone.utc).isoformat(),
            }
        )
        .execute()
    )
    return response.data


# ── Planner helpers ──────────────────────────────────────────────────
def save_daily_plan(
    user_id: str,
    plan_date: str,
    plan_json: dict[str, Any],
) -> dict[str, Any]:
    """Upsert a daily study plan for the given user and date.

    Args:
        user_id: UUID of the learner.
        plan_date: ISO date string (``YYYY-MM-DD``).
        plan_json: Structured plan payload generated by the AI planner.

    Returns:
        The upserted plan row.
    """
    response = (
        get_supabase()
        .table("daily_plans")
        .upsert(
            {
                "user_id": user_id,
                "plan_date": plan_date,
                "plan": plan_json,
            }
        )
        .execute()
    )
    return response.data


# ── Analytics ────────────────────────────────────────────────────────
def get_weak_topics(user_id: str, limit: int = 5) -> list[dict[str, Any]]:
    """Return the topics where the user scores lowest on average.

    Queries the ``topic_scores`` view which aggregates attempt data
    by topic and computes an average score.

    Args:
        user_id: UUID of the learner.
        limit: Maximum number of weak topics to return.

    Returns:
        A list of ``{topic, avg_score}`` dicts, ascending by score.
    """
    response = (
        get_supabase()
        .table("topic_scores")
        .select("topic, avg_score")
        .eq("user_id", user_id)
        .order("avg_score", desc=False)
        .limit(limit)
        .execute()
    )
    return response.data
